language: objective-c
osx_image: xcode9
rvm: 2.4

cache:
  cocoapods: true

install:
- bundle install -j5
- pod repo update
- pod install
- brew install jq

env:
  - SCHEME=iOSTests
  - SCHEME=tvOSTests

script:
  - bundle exec fastlane select_httpbin
  - export DESTINATION="$(./scripts/destination.sh $SCHEME)"
  - xcrun simctl list
  - set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace Demo.xcworkspace -scheme "$SCHEME" -destination "$DESTINATION" build test | xcpretty
